name: Publish new versions to npm

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Npm Install
        run: npm install
        env:
          SA_REPLAY_SKIP_BINARY_DOWNLOAD: false
          SA_SKIP_DOWNLOAD: false

      - name: Check for Npm publish
        run: node ./scripts/npmPublish.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Npm Publish
